
bind: ":8080"
debug: true
debugGin: false
baseURL: http://172.20.117.157:8080/
assetsDir: assets
github:
  owner: panjiang
  repo: crownote
  token: 67416e117f02a71032cc0c3ef99b779ac72838e6
  pre: false