version: "3.7"
services:
  gohazel:
    container_name: gohazel
    image: panjiang/gohazel:latest
    ports:
      - "8080:8080"
    volumes:
      - /data/gohazel/assets:/assets
    command:
      - /gohazel 
      - -addr=:8080
      - -base_url=http://localhost:8080
      - -cache_dir=/assets
      - -proxy_download=false
      - -github_owner=atom
      - -github_repo=atom
      - -github_token=